"""
Django settings for cayanmeisterbetrieb project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import socket
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4@2u-x9_q1caq@n24v+w898*yey8b&ao%&!n665dh$o9l+c04v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '35.198.176.94', 'kfzmeisterbetriebcayan.de', 'www.kfzmeisterbetriebcayan.de']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'frontend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cayanmeisterbetrieb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cayanmeisterbetrieb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydb',
        'USER': 'mycayo',
        'PASSWORD': 'Hzdnielaksdhwk2122',
        'HOST': '127.0.0.1',
        'PORT': 5432,
    }
}

"""
'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydb',
        'USER': 'mycayo',
        'PASSWORD': 'Hzdnielaksdhwk2122',
        'HOST': '127.0.0.1',
        'PORT': 5432,

    }






    'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',


"""

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# MEDIA

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# MAIL STUFF
CAYAN_MAIL = 'ctkfzmeisterbetrieb@gmail.com'
SERVER_MAIL = 'ctmeisterbetriebserver@hotmail.com'
SERVER_MAIL_PASSWORD = 'Jun726duzku22'


# EMail stuff
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = socket.gethostbyname('smtp.outlook.com')
#EMAIL_HOST = 'smtp.outlook.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# we will change this email
#EMAIL_HOST_USER = 'tumurataswebsite@gmail.com'
EMAIL_HOST_USER = 'ctmeisterbetriebserver@hotmail.com'

EMAIL_HOST_PASSWORD = 'Jun726duzku22'
DEFAULT_FROM_EMAIL = 'ctmeisterbetriebserver@hotmail.com'
SERVER_EMAIL = 'ctmeisterbetriebserver@hotmail.com'

#RECAPTCHA
RECAPTCHA_PUBLIC_KEY = '6LcJXu0hAAAAAAhQK1ceRCeNqC-FGdVzav4jJGNX'
RECAPTCHA_PRIVATE_KEY = '6LcJXu0hAAAAAF1xY5jbzlejPda6IWd2asYh92O4'
RECAPTCHA_REQUIRED_SCORE = 0.85
