# Generated by Django 4.0.5 on 2022-09-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField(choices=[(0, 'Schaden am Auto'), (1, 'Problem am Auto'), (2, 'Kostenanfrage'), (3, 'Karriere'), (4, 'Sonstiges')], default=0, verbose_name='Anliegen')),
                ('firstname', models.CharField(max_length=100, verbose_name='Vorname*')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nachname*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('tel', models.CharField(blank=True, max_length=26, null=True, verbose_name='Telefonnummer*')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('inquiry_send_at_date', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('checked', models.BooleanField(default=False, verbose_name='Bearbeitet?')),
            ],
        ),
    ]
